FROM node:16 AS builder
WORKDIR /app
RUN curl -L https://github.com/facuerbin/Microservicio_Reclamos_NestJS/tarball/main | tar xz --strip=1
COPY ./package.json ./
RUN npm install --silent
COPY . .
RUN npm run build

FROM node:16-alpine3.13
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 3005
CMD ["npm", "run", "start:prod"]

